---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-ceph-update
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-ceph-global
    actions:
      - method: replace
        path: .values.conf.storage.osd
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    conf:
      storage:
        osd:
          - data:
              type: directory
              location: /data/openstack-helm/ceph/osd/osd-one 
            journal:
              type: directory
              location: /data/openstack-helm/ceph/osd/journal-one 
      pool:
        target:
          osd: 1
        default:
          crush_rule: replicated_rule
...
---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-ceph-update
  layeringDefinition:
    abstract: false
    layer: site
  storagePolicy: cleartext
data:
  description: Ceph post intall update
  chart_group:
    - ucp-ceph-update
...
