---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-ceph
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-ceph-global
    actions:
      - method: replace
        path: .values.conf.storage.osd
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    conf:
      storage:
        osd:
          - data:
              type: directory
              location: /data/openstack-helm/ceph/osd/osd-one
            journal:
              type: directory
              location: /data/openstack-helm/ceph/osd/journal-one 
      pool:
        target:
          osd: 1
...
