#!/bin/bash

set -x

read -p "Do you want to destroy the exisiting K8S cluster? (y/n)" REPLY
if [ "$REPLY" = "n" ]; then
  exit 0
fi

rm -rf ${WORKSPACE}/collected
rm -rf ${WORKSPACE}/genesis

export KUBECONFIG=/etc/kubernetes/admin/kubeconfig.yaml
kubectl drain --delete-local-data --force $(hostname)

systemctl stop kubelet

while true; do
  if [[ $(df -lh | awk '{ print $6 }' | grep -i docker | grep -v "/var/lib") ]]; then
    echo "unmounted dirs exist"
  else
    break
  fi

  echo "unmounting docker dirs"

  sleep 3

  df -lh | awk '{ print $6 }' | grep -i docker | grep -v "/var/lib" | xargs -I {} umount -f -l {}
done

while true; do
  if [[ $(df -lh | awk '{ print $6 }' | grep -i kubelet) ]]; then
    echo "unmounted dirs exist"
  else
    break
  fi

  echo "unmounting docker dirs"

  sleep 3
  
  df -lh | awk '{ print $6 }' | grep -i kubelet | xargs -I {} umount -f -l {}
done

umount -f -l /run/user/0

mount -a

docker rm -fv $(docker ps -aq)

#Kubernetes
rm -rf /etc/kubernetes
rm -rf /usr/local/bin/kubectl
rm -rf /usr/local/bin/kubelet
rm -rf /var/lib/kubelet
rm -rf /etc/systemd/system/kubelet
rm -rf /etc/systemd/system/kubelet.service
rm -rf /etc/systemd/system/kubelet.service.d/
rm -rf /var/log/pods
rm -rf /var/log/containers
rm -rf /opt/kubernetes/bin/kubelet
rm -rf /var/lib/kubelet

#Boostrap process
rm -rf /var/log/armada

#etcd
rm -rf /var/lib/etcd
rm -rf /etc/genesis/etcd
rm -rf /var/lib/auxiliary-etcd-0
rm -rf /var/lib/auxiliary-etcd-1
rm -rf /var/lib/auxiliary-calico-etcd-0
rm -rf /var/lib/auxiliary-calico-etcd-1
rm -rf /var/lib/calico-etcd
rm -rf /var/lib/kube-etcd

#nova
rm -rf /var/lib/nova/*

# Remove files generated by Promenade
rm -rf /etc/cni
rm -rf /etc/coredns
rm -rf /etc/etcd
rm -rf /etc/genesis
rm -rf /var/lib/etcd
rm -rf /var/lib/kubelet/pods
rm -rf /etc/promenade
rm -rf /etc/promenade-manifest

#ceph
rm -rf /data/openstack-helm
rm -rf /var/lib/openstack-helm
rm -rf /var/lib/ceph/journal/*

